// ----- types -----

const ADD_TOURIST = 'ADD_TOURIST';
const ADD_TOURIST_FLIGHT = 'ADD_TOURIST_FLIGHT'
const DEL_TOURIST = 'DELETE_TOURIST';
const DEL_TOURIST_FLIGHT = 'DEL_TOURIST_FLIGHT';
const DEL_FLIGHT_FROM_ALL_TOURISTS= 'DEL_FLIGHT_FROM_ALL_TOURISTS'

export default{
    ADD_TOURIST,
    ADD_TOURIST_FLIGHT,
    DEL_TOURIST,
    DEL_TOURIST_FLIGHT,
    DEL_FLIGHT_FROM_ALL_TOURISTS
}